// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcwhhzzrtpxotytzziaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjd2hoenpydHB4b3R5dHp6aWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjY1NjUsImV4cCI6MjA2NDc0MjU2NX0.gVeEDktsP0-P8YMfxhxGvlWoiB4ee6pTxTfqBDq4woA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);